### ISSUE TITLE
Add github templates

### ISSUE THREAD

**Issue by joshpennington** [joshminnie/workspace#24]
We should have templates for the different types of Issues that we could have submitted. Specifically one for requesting new services to be added as well as bug reports and feature requests

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by joshpennington** [comment]
@joshminnie I have a basic service add request form put in that you can preview here:

https://github.com/joshminnie/workspace/blob/create-github-templates/.github/ISSUE_TEMPLATE/service_request.yml

What other templates should we add and what fields should we have on them> I am thinking we should have something for bug reports and other general feature requests.

**Comment by joshminnie** [comment]
I like the idea of this! Let's create a pull request to start using this. We may need to refine a bit, but this is a great starting point.

We should also be including GitHub templates for pull requests at some point, but let's start small.
