### ISSUE TITLE
Add .gitignore file to generator

### ISSUE THREAD

**Issue by joshminnie** [joshminnie/workspace#40]
Services may have different requirements for what should be ignored, not just by docker, but also git. Also, we need to document each service usage as well.

We should add a `.gitignore` and `README.md` file to the generator script.

**Comment by joshpennington** [comment]
I can put together a starter version of the README.md file based on what I have done for some of the other services. What should go into a .gitignore file when generated? A blank file?

**Comment by joshminnie** [comment]
I think a blank `.gitignore` is going to be fine in this case, but I can see value in having it there so a user knows that they can add more ignores at that level, similar to some of the services that have been added manually.

**Comment by joshminnie** [comment]
@joshpennington I have some work already done with this, provide your "template" README here and I will add it.
