### ISSUE TITLE
Creating new service allows creation of invalid container name

### ISSUE THREAD

**Issue by joshpennington** [joshminnie/workspace#5]
Entering command `./workspace service new -i mariadb mariadb:10.4.19` succeeds, but the container is unable to be started because the service name contains invalid characters

While debugging:
`~/dev/tools/workspace/services/mariadb:10.4.19(add-file-generator-for-services) » docker-compose up                                                    joshp@Joshs-MacBook-Pro
ERROR: The Compose file './docker-compose.yml' is invalid because:
Invalid service name 'mariadb:10.4.19' - only [a-zA-Z0-9\._\-] characters are allowed`

**Comment by joshminnie** [comment]
The reason for this is because the command is wrong. `-i` is the switch for the name of the base image to template the container from. The proper command would be:
```shell
$  ./workspace service new mariadb -i mariadb:10.4.19
```
